# Project metadata (name, version, description, license, authors, URLs) is
# declared in pyproject.toml under [project]. This file keeps only the
# setuptools-specific package discovery and optional-dependency configuration.

[metadata]
author = ApiGear
author_email = info@apigear.io

[options]
package_dir =
    = src
packages = find:

[options.packages.find]
where = src

[options.extras_require]
dev =
    pytest
    pytest-cov
    ruff
examples =
    starlette
    uvicorn
    websockets